const data = {
  cars: [
    {
      id: 1,
      name: 'Chevrolet',
      image: 'https://res.cloudinary.com/dltibnft3/image/upload/v1689344750/vehicle-images/chevrolet-aveo_nfxp4q.png',
      service: 'Business',
      type: 'Economic',
      description: 'Lorem ipsum dolor sit amet, consectetur adipscing elit, sed do eiusmod tempor incididunt ut',
      seats: 5,
      option: 'Manual',
      luggage: 2,
      price: 800,
      kmFare: 20,
    },
    {
      id: 2,
      name: 'Mercedez',
      image: 'https://res.cloudinary.com/dltibnft3/image/upload/v1689344751/vehicle-images/mercedes-e-class_mxj1ea.png',
      service: 'Business',
      type: 'Luxury',
      description: 'Lorem ipsum dolor sit amet, consectetur adipscing elit, sed do eiusmod tempor incididunt ut',
      seats: 4,
      option: 'Automatic',
      luggage: 3,
      price: 1200,
      kmFare: 30,
    },
    {
      name: 'Ford',
      image: 'https://res.cloudinary.com/dltibnft3/image/upload/v1689350864/vehicle-images/ford-eco-sport_hetxiv.png',
      service: 'Business',
      type: 'Spacious',
      description: 'Lorem ipsum dolor sit amet, consectetur adipscing elit, sed do eiusmod tempor incididunt ut',
      seats: 3,
      option: 'Automatic',
      luggage: 3,
      price: 1200,
      kmFare: 30,
      id: 5,
    },
  ],
};

export default data;
